import type { NextPage } from 'next';
import Head from 'next/head';
import Present from '../Components/Present';
import { useEnglish } from '../context/englishContext';

const Home: NextPage = () => {
  const { english } = useEnglish();
  return (
    <div className='h-screen w-screen snap-y snap-proximity overflow-scroll scroll-smooth overflow-x-hidden scrollbar-hide p-0 m-0
      flex flex-col md:items-end w-full bg-black'>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Present />
    </div>
  )
}

export default Home
